name: mealmate
description: Diploma project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  flutter_svg_provider: ^1.0.7
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  http: ^1.2.0
  dio: ^5.4.0
  google_sign_in: ^6.2.1
  url_launcher: ^6.2.4
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/diets/

  fonts:
    - family: Abhaya Libre
      fonts:
        - asset: assets/fonts/AbhayaLibreBold.ttf
          weight: 700
        - asset: assets/fonts/AbhayaLibreRegular.ttf
          weight: 400
    - family: Manrope
      fonts:
        - asset: assets/fonts/ManropeRegular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
    - family: Rubik
      fonts:
        - asset: assets/fonts/RubikRegular.ttf
          weight: 400
    - family: Abhaya Libre Medium
      fonts:
        - asset: assets/fonts/AbhayaLibreMedium.ttf
          weight: 500
    - family: Abhaya Libre SemiBold
      fonts:
        - asset: assets/fonts/AbhayaLibreSemiBold.ttf
          weight: 600
    - family: Abhaya Libre ExtraBold
      fonts:
        - asset: assets/fonts/AbhayaLibreExtraBold.ttf
          weight: 800
    - family: Alfa Slab One
      fonts:
        - asset: assets/fonts/AlfaSlabOneRegular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterBold.ttf
          weight: 700
